### PR TITLE
Senior DevOps Engineer: Docker

### PR DESCRIPTION
**Pull request by cytopia**
# Coding Challenge for Senior DevOps Engineer: Docker

This is a first draft for a coding challenge about Docker and Docker Compose.

It might be a good idea to have different coding challenges about different topics, so that the applicant can choose from various topics.

### Review

* Check if the scope is fine
* Check if everything is clear and understandable
* Check for typos

### Todo

* Provide very basic FE application
* Provide very basic BE application

##### FE

FE might simply fetch an url from any backend an just output what it received (including FE hostname).
Should also have a config file for hostname/IP and port of backend.

##### BE

BE should simply fetch some value from DB and provide it as an url that can be fetched for the FE .
Should also have a config file for hostname/IP, port and credentials for DB.

### CODE REVIEW

**Review by danvaida — CHANGES_REQUESTED** [review]
it's not clear for me what is it that you're trying to get the candidate to achieve with this and how exactly to do that... let's have a short talk about it, to clarify things.

**Comment by ronny-panknin-flaconi** [comment]
Possibly we can extend it but it looks good for the first iteration. 👍

**Review by snovikov — COMMENTED** [review]
Looks good for me. But is there any ticket with Acceptance criteria for that?

**Comment by cytopia** [comment]
@snovikov did you have a look at the Readme [Required functionality](https://github.com/Flaconi/coding-challenges/blob/5bb15d0f571a0bef1c83b9e38e3f4d94ff3ad3d3/senior-devops-engineer/docker.md#required-functionality)?

**Review by snovikov — APPROVED** [review]
I think the goal is pretty clear

**Pull request merged**
