### PR TITLE
terraform.md

### PR DESCRIPTION
**Pull request by prasannaramaswamy**

### CODE REVIEW

**Comment by snovikov** [comment]
Looks good for me. @cytopia ???

**Comment by danvaida** [comment]
> Looks good for me. @cytopia ???

Shouldn't the file be renamed as well?

**Review by cytopia — CHANGES_REQUESTED** [review]
As @danvaida has also already mentioned, the file should be renamed to `terraform-aws.md`

**Comment by cytopia** [comment]
Closing in favour of the TF challenge which got recently merged.

**Pull request closed without merging**
